name_or_path: /mnt/data/anhnh2220/dat/weighted-Ra_DPO/output/mistral-7b-sft
tokenizer_name_or_path: /mnt/data/anhnh2220/dat/weighted-Ra_DPO/output/mistral-7b-sft
archive: null
block_name: MistralDecoderLayer

policy_dtype: bfloat16
fsdp_policy_mp: bfloat16
reference_dtype: float16